-- Generated from data/rya_py_2026.csv — do not edit by hand; re-run script.
-- https://www.rya.org.uk — data © Royal Yachting Association (use per your licence).

alter table public.rya_class_py
  add column if not exists category text,
  add column if not exists crew_count smallint,
  add column if not exists rig text,
  add column if not exists spinnaker text,
  add column if not exists keel text,
  add column if not exists engine text;

comment on column public.rya_class_py.display_name is 'RYA Type (class name as published).';
comment on column public.rya_class_py.py is 'RYA Portsmouth Yardstick handicap.';
comment on column public.rya_class_py.category is 'RYA Category (e.g. Dinghy, Keelboat).';
comment on column public.rya_class_py.crew_count is 'RYA No of crew.';
comment on column public.rya_class_py.rig is 'RYA Rig.';
comment on column public.rya_class_py.spinnaker is 'RYA Spinnaker.';
comment on column public.rya_class_py.keel is 'RYA Keel.';
comment on column public.rya_class_py.engine is 'RYA Engine (when provided in source data).';

comment on table public.rya_class_py is 'System Portsmouth handicaps keyed by normalized class name; seeded from repo data CSV (Royal Yachting Association).';

alter table public.rya_class_py
  add constraint rya_class_py_crew_count_check
  check (crew_count is null or (crew_count >= 1 and crew_count <= 20))
  not valid;

alter table public.rya_class_py validate constraint rya_class_py_crew_count_check;

insert into public.rya_class_py (class_key, display_name, py, category, crew_count, rig, spinnaker, keel, engine)
values
  ('2_4mr', '2.4mR', 1235, 'Keelboat', 1, 'Sloop', 'None', 'Fin', null),
  ('2000', '2000', 1122, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('29er', '29er', 900, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('4000', '4000', 926, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('420', '420', 1100, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('505', '505', 892, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('a_class', 'A CLASS', 684, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('a_class_non_foiling', 'A CLASS (NON-FOILING)', 695, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('a_classic_straight_or_constant_curve_foils', 'A-Classic (straight or constant curve foils)', 695, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('albacore', 'ALBACORE', 1037, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('alto', 'ALTO', 910, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('b14', 'B14', 858, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('blaze', 'BLAZE', 1030, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('blaze_fire', 'BLAZE FIRE', 1050, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('british_moth', 'BRITISH MOTH', 1160, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('buzz', 'BUZZ', 1009, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('byte_ci', 'BYTE CI', 1223, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('byte_cii', 'BYTE CII', 1123, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('cadet', 'CADET', 1455, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('canoe_international', 'CANOE INTERNATIONAL', 858, 'Dinghy', 1, 'Sloop', 'None', 'CB', null),
  ('catapult', 'Catapult', 898, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('challenger', 'CHALLENGER', 1175, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('comet', 'COMET', 1208, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('comet_trio_mk_1', 'COMET TRIO (Mk 1)', 1082, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('comet_trio_mk_2', 'COMET TRIO (Mk 2)', 1053, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('comet_xtra', 'COMET XTRA', 1210, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('contender', 'CONTENDER', 973, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('dart_15', 'Dart 15', 916, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('dart_15_sport_solo', 'Dart 15 sport solo', 904, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('dart_18', 'Dart 18', 795, 'Multihull', 2, 'Sloop', 'None', 'None', null),
  ('devoti_d_one', 'DEVOTI D-ONE', 957, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('devoti_d_zero', 'DEVOTI D-ZERO', 1029, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('devoti_d_zero_black_rig', 'DEVOTI D-ZERO BLACK RIG', 1051, 'Dinghy', 1, 'Una', 'None', 'None', null),
  ('enterprise', 'ENTERPRISE', 1137, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('europe', 'EUROPE', 1140, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('finn', 'FINN', 1049, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('fireball', 'FIREBALL', 960, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('firefly', 'FIREFLY', 1178, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('flying_fifteen', 'FLYING FIFTEEN', 1028, 'Keelboat', 2, 'Sloop', 'Conventional', 'Fin', null),
  ('flying_fifteen_classic_1_2700', 'FLYING FIFTEEN CLASSIC (1-2700)', 1079, 'Keelboat', 2, 'Sloop', 'Conventional', 'Fin', null),
  ('flying_fifteen_silver_2701_3400', 'FLYING FIFTEEN SILVER (2701-3400)', 1051, 'Keelboat', 2, 'Sloop', 'Conventional', 'Fin', null),
  ('fusion_pro', 'Fusion pro', 1281, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('fusion_pro_gen', 'FUSION PRO GEN', 1275, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'None', null),
  ('fusion_pro_spinnaker', 'Fusion pro Spinnaker', 1275, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('gp14', 'GP14', 1145, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('graduate', 'GRADUATE', 1110, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('gull', 'GULL', 1385, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('hadron_h2', 'HADRON H2', 1045, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('hansa_303_singlehanded', 'HANSA 303 SINGLEHANDED', 1570, 'Dinghy', 1, 'Una', 'None', 'None', null),
  ('hansa_liberty', 'HANSA LIBERTY', 1411, 'Dinghy', 1, 'Una', 'None', 'None', null),
  ('hartley_zenith', 'HARTLEY ZENITH', 1051, 'Dinghy', 1, 'Sloop', 'None', 'CB', null),
  ('hornet', 'HORNET', 950, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('hurricane_5_9_sx', 'Hurricane 5.9 SX', 680, 'Multihull', 2, 'Sloop', 'None', 'None', null),
  ('icon', 'Icon', 976, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('ilca_4', 'ILCA 4', 1218, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('ilca_6', 'ILCA 6', 1156, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('ilca_7', 'ILCA 7', 1103, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('illusion', 'ILLUSION', 1285, 'Dinghy', 1, 'Sloop', 'Conventional', 'Fin', null),
  ('iso', 'ISO', 940, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('javelin', 'JAVELIN', 944, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('k1', 'K1', 1060, 'Keelboat', 1, 'Sloop', 'None', 'Fin', null),
  ('k6', 'K6', 900, 'Keelboat', 2, 'Sloop', 'Asymmetric', 'Fin', null),
  ('kestrel', 'KESTREL', 1042, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('lark', 'LARK', 1060, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('laser', 'LASER', 1103, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('laser_4_7', 'LASER 4.7', 1218, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('laser_eps', 'LASER EPS', 1033, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('laser_ii', 'LASER II', 1085, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('laser_radial', 'LASER RADIAL', 1156, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('laser_stratos', 'LASER STRATOS', 1108, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('lightning_368', 'LIGHTNING 368', 1171, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('megabyte', 'MEGABYTE', 1058, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('melges_15', 'MELGES 15', 994, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('merlin_rocket', 'MERLIN-ROCKET', 980, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('miracle', 'MIRACLE', 1196, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('mirror', 'MIRROR', 1364, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('mirror_no_spinnaker', 'MIRROR NO SPINNAKER', 1376, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('mirror_s_h', 'MIRROR S/H', 1376, 'Dinghy', 1, 'Sloop', 'None', 'CB', null),
  ('musto_skiff', 'MUSTO SKIFF', 830, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('national_12', 'NATIONAL 12', 1070, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('ok', 'OK', 1092, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('optimist', 'OPTIMIST', 1629, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('osprey', 'OSPREY', 932, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('phantom', 'PHANTOM', 998, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rooster_8_1', 'ROOSTER 8.1', 1016, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_100_10_2', 'RS 100 10.2', 981, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('rs_100_8_4', 'RS 100 8.4', 1002, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('rs_200', 'RS 200', 1053, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('rs_300', 'RS 300', 965, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_400', 'RS 400', 945, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('rs_500', 'RS 500', 963, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('rs_600', 'RS 600', 921, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_700', 'RS 700', 845, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('rs_800', 'RS 800', 797, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('rs_aero_5', 'RS Aero 5', 1141, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_aero_6', 'RS Aero 6', 1098, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_aero_7', 'RS Aero 7', 1062, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_aero_9', 'RS Aero 9', 1005, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_feva_xl', 'RS FEVA XL', 1248, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('rs_tera_pro', 'RS TERA PRO', 1368, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_tera_sport', 'RS TERA SPORT', 1452, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('rs_vareo', 'RS VAREO', 1095, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('rs_vision', 'RS VISION', 1150, 'Dinghy', 2, 'Sloop', 'Asymmetric', 'CB', null),
  ('scorpion', 'SCORPION', 1042, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('seafly', 'SEAFLY', 1074, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('shockwave_f18', 'Shockwave F18', 719, 'Multihull', 2, 'Sloop', 'None', 'None', null),
  ('snipe', 'SNIPE', 1104, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('solo', 'SOLO', 1139, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('solution', 'SOLUTION', 1112, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('spitfire_solo_without_jib', 'Spitfire Solo (without jib)', 745, 'Multihull', 1, 'Una', 'Asymmetric', 'None', null),
  ('splash', 'SPLASH', 1247, 'Dinghy', 1, 'Una', 'None', 'None', null),
  ('sprint_15_dx', 'Sprint 15 DX', 924, 'Multihull', 1, 'Una', 'None', 'None', null),
  ('sprint_15_sport', 'SPRINT 15 SPORT', 904, 'Multihull', 1, 'Sloop', 'None', 'None', null),
  ('streaker', 'STREAKER', 1121, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('supernova', 'SUPERNOVA', 1075, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('tasar', 'TASAR', 1022, 'Dinghy', 2, 'Sloop', 'None', 'CB', null),
  ('topper', 'TOPPER', 1369, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('topper_4_2', 'TOPPER 4.2', 1450, 'Dinghy', 1, 'Una', 'None', 'CB', null),
  ('vortex', 'VORTEX', 950, 'Dinghy', 1, 'Una', 'Asymmetric', 'CB', null),
  ('wanderer', 'WANDERER', 1201, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null),
  ('wayfarer', 'WAYFARER', 1107, 'Dinghy', 2, 'Sloop', 'Conventional', 'CB', null)
on conflict (class_key) do update set
  display_name = excluded.display_name,
  py = excluded.py,
  category = excluded.category,
  crew_count = excluded.crew_count,
  rig = excluded.rig,
  spinnaker = excluded.spinnaker,
  keel = excluded.keel,
  engine = excluded.engine;
